version: '3.6'

services:
  bot:
    privileged: true
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - /var/lib/orange:/bot/
    command: bash -c "python3 run.py"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.7
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d telebot -U ${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    restart: always
    env_file:
      - .env
    privileged: true
    environment:
      POSTGRES_DB: telebot
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata/
    volumes:
      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
